name: FiguresFix
version: ${project.version}
main: ru.leymooo.figuresfix.FiguresFix
author: Leymooo
depend: [ProtocolLib]
softdepend: [ViaVersion]
commands:
  figuresfix:
    permission: figuresfix.command